WIP: Blob streams
ankoh/dashql-legacy pull request #40
Opened 2021-03-10 12:10 UTC by Dakror

2021-03-10 12:14 UTC, ankoh commented on webdb/src/webdb_bindings.ts
> +// As a global function because when passing the object to the webworker it turns into a POJO (?)
Yes, that's a problem. Maybe just turn the blobstream into an interface?

2021-03-10 12:14 UTC, ankoh commented on webdb/src/async_webdb.ts
> +    /// Ping the worker thread
Comment

2021-03-10 12:15 UTC, ankoh commented on webdb/src/worker_node.ts
> +                dashql_blob_stream_underflow: function (blobId: number, buf: number, size: number): number {
Ok here for now but we should probably just move this to a dedicated node_runtime file or so

2021-03-10 12:17 UTC, ankoh requested changes
Very nice!

2021-03-10 12:40 UTC, Dakror commented on webdb/src/worker_node.ts
> +                dashql_blob_stream_underflow: function (blobId: number, buf: number, size: number): number {
The problem here is the circular referencing of runtime and bindings. if i move the runtime to a new file i somehow need to give it the bindings, but also the other way around. whats the best solution there?

2021-03-10 12:42 UTC, ankoh commented on webdb/src/worker_node.ts
> +                dashql_blob_stream_underflow: function (blobId: number, buf: number, size: number): number {
Ah I see. Then lets leave it like that at the moment. I'd probably just move the blob map into the runtime as well and then pass the runtime to the bindings on init.

2021-03-11 12:06 UTC, ankoh commented on benchmarks/src/iterator_benchmark.ts
> +const db = new webdb.WebDB(logger, new webdb.DefaultWebDBRuntime(), wasmPath);
static variable now, no need for new

2021-03-11 12:06 UTC, ankoh commented on benchmarks/src/proxy_benchmark.ts
> +const db = new webdb.WebDB(logger, new webdb.DefaultWebDBRuntime(), wasmPath);
static variable now, no need for new

2021-03-11 12:06 UTC, ankoh commented on webdb/package.json
> +        "build": "webpack --mode=development && node ./gendts.js",
production

2021-03-11 12:09 UTC, ankoh requested changes

2021-03-11 12:09 UTC, ankoh commented on webdb/test/webdb_bindings.test.ts
> +    db = new webdb.WebDB(logger, new webdb.DefaultWebDBRuntime(), path.resolve(__dirname, '../src/webdb_wasm.wasm'));
static pojo now

2021-03-11 12:09 UTC, ankoh commented on webdb/test/proxy.test.ts
> +    db = new webdb.WebDB(logger, new webdb.DefaultWebDBRuntime(), path.resolve(__dirname, '../src/webdb_wasm.wasm'));
here as well

2021-03-11 13:15 UTC, ankoh reviewed
Awesome :+1:

2021-03-11 13:19 UTC, merged